/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Main {
    public static void main(String[] args) {

        Review review1 = new Review("best Restaurant ", "NoBody", 5);
        System.out.println(review1.toString());

        Resturant bite = new Resturant("bite", 5, "$$");
        System.out.println(bite.toString());



        }
}
