/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Main {
    public static void main(String[] args) {

        Review review1 = new Review("my Fav one ", "NoBody", 5);
        System.out.println(review1.toString());

        Restaurant buff = new Restaurant("Buff", 5, "$$");
        System.out.println(buff.toString());



        }
}
