/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Main {
    public static void main(String[] args) {

        var buffShop = new Shop("name","$$","My Fav");
        Review review1 = new Review("my Fav one ", "NoBody", 5) {

        };
        System.out.println(review1.toString());

        Restaurant buff = new Restaurant("Buff", 5, "$$");
        var theater = new Theater("theater");
        theater.addMovie("lalalala");
        theater.addMovie("lelelelelele");
        theater.removeMovie("lalalala");
        System.out.println(theater.toString());
        System.out.println(buff.toString());
        System.out.println(buffShop.toString());



    }
}