/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {

//    @Test void someLibraryMethodReturnsTrue() {
//        Library classUnderTest = new Library();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
@Test
    public void testReview(){
        Review review1 = new Review("Best Restaurant", "SomeOne", 5);
//
        Assertions.assertEquals( "Review{body='Best Restaurant', author='SomeOne', stars=5}", review1.toString());
    }
    public void testResturant(){
     var bite = new Resturant("bite", 5, "$$");

    }

    @Test public void toStringTest(){
        assertTrue(true, ("Restaurant{name='bite', stars=5, price='$$'}"));
    }
}
