/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


@Test
    public void testReview(){
        Review review1 = new Review("Fav one", "noOne", 5);
//
        Assertions.assertEquals( "Review{body='Fav one', author='noOne', stars=5}", review1.toString());
    }
    public void testRestaurant(){
     var buff = new Restaurant("Buff", 5, "$$");

    }

    @Test public void toStringTest(){
        assertTrue(true, ("Restaurant{name='Buff', stars=5, price='$$'}"));
    }
}
